services:
  #PostgreSQL Database for the application
  postgres:
    image:  postgres:latest
    restart: always
    container_name: postgres
    ports:
      - "5432:5432"
    environment:
      POSTGRES_DB: postgres
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: 123456
    networks:
      - app-network
    volumes:  #กำหนดการแมปไฟล์
      - postgres-data:/var/lib/postgresql/data
      - ./init-postgres.sh:/docker-entrypoint-initdb.d/init-postgres.sh
    healthcheck:  #ตรวจสอบสถานะของคอนเทนเนอร์
      test: ["CMD-SHELL", "pg_isready -U postgres"]
      interval: 10s
      timeout: 5s
      retries: 10

networks:
  app-network:
    external: true

volumes:
  postgres-data: